//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Json {
  
  
  public class MountConfig : IGeneratorObject {
    
    // 索引
    public int Id { get; private set; }
    
    public void Read(ConfigElement element) {
      this.Id = GeneratorUtility.Get(element, "Id", this.Id);
      this.OnInit();
    }
    
    protected virtual void OnInit() {
    }
    
    public static MountConfig[] Load() {
      return Load<MountConfig>();
    }
    
    public static T[] Load<T>()
      where T : MountConfig, new () {
      return GeneratorUtility.Load<T>("MountsConfig", "Mount");
    }
  }
}
