-- local emptyFn = System.emptyFn
-- local SystemTypeof = System.typeof
-- local BridgeMonoBehaviour = LuaFramework.LuaBehaviour
-- LuaFramework.LuaBehaviour = nil

-- local setmetatable = setmetatable
-- local getmetatable = getmetatable
-- local rawget = rawget
-- local rawset = rawset
-- local type = type
-- local sbyte = string.byte
-- local typeof = typeof
-- local pcall = pcall

-- local LuaBehaviour = System.define("LuaFramework.LuaBehaviour", {
--   __ctor__ = emptyFn,
--   class = "C",
--   GetType = System.Object.GetType,
--   print = UnityEngineMonoBehaviour.print,
--   Awake = emptyFn,
--   Start = emptyFn,
--   Update = emptyFn,
--   FixedUpdate = emptyFn,
--   LateUpdate = emptyFn,
--   ToString = function (this)
--     return sformat("%s (%s)", this.ref.gameObject.name, this.__name__)
--   end,
-- })
-- SystemTypeof(LuaBehaviour)[1] = BridgeMonoBehaviour

-- local function getMonoBehaviourFunction(metatableOfMonoBehaviour, name)
--   return metatableOfMonoBehaviour[name]   
-- end

-- local metatableOfMonoBehaviour = getmetatable(BridgeMonoBehaviour) 
-- setmetatable(LuaBehaviour, {
--   __index = function (t, k)
--     if type(k) == "string" then
--       local c = sbyte(k, 1)
--       if c ~= 95 and c ~= 46 then -- not '.' or '_'
--         local ok, f = pcall(getMonoBehaviourFunction, metatableOfMonoBehaviour, k)
--         if ok then
--           local v = function (this, ...)
--             return f(this.ref, ...)
--           end
--           t[k] = v
--           return v
--         end
--       end
--     end
--     return nil
--   end
-- })
