//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Protobuf {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class GlobalProto : IGeneratorObject {
    
    // 名字字数限制
    [ProtoMember(1)]
    public int NameLimit;
    
    // 命中修正系数
    [ProtoMember(2)]
    public double HitCorrection;
    
    // 等级区间
    [ProtoMember(3)]
    public LevelRange_ LevelRange;
    
    // 初始任务获得道具
    [ProtoMember(4)]
    public int[] InitItems;
    
    // 缓存静态实例减少开销
    private static GlobalProto _obj;
    
    public virtual void OnInit() {
    }
    
    public static GlobalProto Load() {
      return _obj = (_obj == null ? Load<GlobalProto>() : _obj);
    }
    
    public static T Load<T>()
      where T : GlobalProto, new () {
      return GeneratorUtility.Load<T>("GlobalProto");
    }
    
    [ProtoContract()]
    public sealed class LevelRange_ : IGeneratorObject {
      
      [ProtoMember(1)]
      public int Min;
      
      [ProtoMember(2)]
      public int Max;
      
      public void OnInit() {
      }
    }
  }
}
