//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Protobuf {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class HeroProto : IGeneratorObject {
    
    // 索引
    [ProtoMember(1)]
    public int Id;
    
    // 坐骑
    [ProtoMember(2)]
    public int MountId;
    
    // 性别
    [ProtoMember(3)]
    public bool Sex;
    
    // 身高
    [ProtoMember(4)]
    public double Height;
    
    // 武器
    [ProtoMember(5)]
    public int[] Weapons;
    
    // 主要属性
    [ProtoMember(6)]
    public Property_ Property;
    
    // 背包
    [ProtoMember(7)]
    public Bag_[] Bags;
    
    // 缓存静态实例减少开销
    private static HeroProto[] _obj;
    
    public virtual void OnInit() {
    }
    
    public static HeroProto[] Load() {
      return _obj = (_obj == null ? Load<HeroProto>() : _obj);
    }
    
    public static T[] Load<T>()
      where T : HeroProto, new () {
      return GeneratorUtility.Load<T>("HerosConfig", "Hero");
    }
    
    [ProtoContract()]
    public sealed class Property_ : IGeneratorObject {
      
      [ProtoMember(1)]
      public int Hp;
      
      [ProtoMember(2)]
      public int Magic;
      
      public void OnInit() {
      }
    }
    
    [ProtoContract()]
    public sealed class Bag_ : IGeneratorObject {
      
      [ProtoMember(1)]
      public int Id;
      
      [ProtoMember(2)]
      public int Count;
      
      public void OnInit() {
      }
    }
  }
}
