//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Protobuf {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class MountProto : IGeneratorObject {
    
    // 索引
    [ProtoMember(1)]
    public int Id;
    
    // 缓存静态实例减少开销
    private static MountProto[] _obj;
    
    public virtual void OnInit() {
    }
    
    public static MountProto[] Load() {
      return _obj = (_obj == null ? Load<MountProto>() : _obj);
    }
    
    public static T[] Load<T>()
      where T : MountProto, new () {
      return GeneratorUtility.Load<T>("MountsProto", "Mount");
    }
  }
}
