//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Protobuf {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class PersonProto : IGeneratorObject {
    
    // 头部
    [ProtoMember(1)]
    public Header_ header;
    
    // 账号
    [ProtoMember(2)]
    public int id;
    
    // 名称
    [ProtoMember(3)]
    public string name;
    
    // 年龄
    [ProtoMember(4)]
    public int age;
    
    // 邮箱
    [ProtoMember(5)]
    public string email;
    
    // 数组
    [ProtoMember(6)]
    public int[] arrays;
    
    // 数组2
    [ProtoMember(7)]
    public string[] array2s;
    
    // 头部2
    [ProtoMember(8)]
    public Header2_ header2;
    
    // 缓存静态实例减少开销
    private static PersonProto _obj;
    
    public virtual void OnInit() {
    }
    
    public static PersonProto Load() {
      return _obj = (_obj == null ? Load<PersonProto>() : _obj);
    }
    
    public static T Load<T>()
      where T : PersonProto, new () {
      return GeneratorUtility.Load<T>("PersonProto");
    }
    
    [ProtoContract()]
    public sealed class Header_ : IGeneratorObject {
      
      [ProtoMember(1)]
      public int cmd;
      
      [ProtoMember(2)]
      public int seq;
      
      public void OnInit() {
      }
    }
    
    [ProtoContract()]
    public sealed class Header2_ : IGeneratorObject {
      
      [ProtoMember(1)]
      public int cmd;
      
      [ProtoMember(2)]
      public int seq;
      
      [ProtoMember(3)]
      public string ss;
      
      public void OnInit() {
      }
    }
  }
}
