//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpGeneratorForProton.Protobuf {
  using ProtoBuf;
  
  
  [ProtoContract()]
  public class TextProto : IGeneratorObject {
    
    // 文本1
    [ProtoMember(1)]
    public string Text_1;
    
    // 文本2
    [ProtoMember(2)]
    public string Text_2;
    
    // 文本3
    [ProtoMember(3)]
    public string Text_3;
    
    // 缓存静态实例减少开销
    private static TextProto _obj;
    
    public virtual void OnInit() {
    }
    
    public static TextProto Load() {
      return _obj = (_obj == null ? Load<TextProto>() : _obj);
    }
    
    public static T Load<T>()
      where T : TextProto, new () {
      return GeneratorUtility.Load<T>("TextProto");
    }
  }
}
